# Generated by Django 4.0.6 on 2022-07-17 18:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Keyword',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='StatCard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('card_front', models.ImageField(upload_to='')),
                ('card_back', models.ImageField(upload_to='')),
            ],
        ),
        migrations.CreateModel(
            name='MalifauxModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('keyword', models.ManyToManyField(to='malifauxModel.keyword')),
                ('stat_card', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='malifauxModel.statcard')),
            ],
        ),
    ]
