# Generated by Django 4.0.6 on 2022-07-17 20:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('malifauxModel', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='statcard',
            name='pdf',
            field=models.FileField(default=None, upload_to='stat_card_pdfs'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='statcard',
            name='card_back',
            field=models.ImageField(upload_to='stat_cards'),
        ),
        migrations.AlterField(
            model_name='statcard',
            name='card_front',
            field=models.ImageField(upload_to='stat_cards'),
        ),
    ]
