# Generated by Django 4.0.6 on 2022-07-17 21:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('malifauxModel', '0002_statcard_pdf_alter_statcard_card_back_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='statcard',
            name='pdf',
        ),
    ]
