# Generated by Django 4.0.6 on 2022-07-17 21:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('malifauxModel', '0003_remove_statcard_pdf'),
    ]

    operations = [
        migrations.AddField(
            model_name='statcard',
            name='name',
            field=models.CharField(default='Unnamed', max_length=50),
        ),
    ]
