# Generated by Django 4.0.6 on 2022-07-18 20:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('malifauxModel', '0006_ability_characteristic_faction_keywordadmin_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='malifauxmodel',
            name='health',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
