# Generated by Django 4.0.6 on 2022-07-18 20:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('malifauxModel', '0007_malifauxmodel_health'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ability',
            name='description',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='action',
            name='description',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='trigger',
            name='description',
            field=models.TextField(),
        ),
    ]
