# Generated by Django 4.0.6 on 2022-08-14 11:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('malifauxModel', '0008_alter_ability_description_alter_action_description_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='malifauxmodel',
            name='cost',
            field=models.IntegerField(default=15),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='action',
            name='stat',
            field=models.CharField(max_length=50),
        ),
    ]
